version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/edc-marketplace

permissions:
- object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
# During the BeforeInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
# During the AfterInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu
# During the ApplicationInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu